/********************************************************************************
** Form generated from reading UI file 'ceohomescreen.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CEOHOMESCREEN_H
#define UI_CEOHOMESCREEN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ceohomescreen
{
public:
    QPushButton *btnManageProjectsCEO;
    QPushButton *btnHomeCEO;
    QPushButton *button1;
    QPushButton *btnManageEmpCEO;
    QGroupBox *homeControlCEO;
    QLabel *label;
    QLabel *label_4;
    QFrame *frame;
    QLabel *label_7;
    QLabel *lblNotStartedCount_3;
    QLabel *label_8;
    QFrame *frame_3;
    QLabel *label_13;
    QLabel *lblInProgressCount_3;
    QFrame *frame_2;
    QLabel *label_14;
    QLabel *lblCompletedCount_3;
    QFrame *frame_4;
    QLabel *lblNameHeader_3;
    QLabel *lblRoleHeader_3;
    QFrame *line_3;
    QSplitter *splitter_3;
    QLabel *lblName_3;
    QLabel *lblGender_3;
    QLabel *lblAddress_3;
    QLabel *lblDepartment_3;
    QLabel *lblRole_3;
    QLabel *lblUsername_3;
    QLabel *label_15;
    QLabel *pUserAvatar;
    QGroupBox *ucManageEmployeeControl;
    QPushButton *btnEditEmployee;
    QLabel *label_16;
    QPushButton *btnDeleteEmployee;
    QTableView *dgEmployee;
    QPushButton *btnAddEmployee;
    QGroupBox *groupBox;
    QLineEdit *txtEmployeeName;
    QLineEdit *txtPassword;
    QComboBox *cbUserRole;
    QComboBox *cbDepartment;
    QComboBox *cbGender;
    QLineEdit *txtUsername;
    QTextEdit *txtAddress;
    QLabel *label_9;
    QLabel *label_2;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_3;
    QLabel *label_10;
    QLabel *label_11;
    QPushButton *btnLoad;
    QGroupBox *usManageProjectControl;
    QTableView *dgProject_2;
    QPushButton *btnEditProject_2;
    QPushButton *btnDeleteProject_2;
    QLabel *label_17;
    QPushButton *btnAddProject_2;
    QPushButton *btnAssignUser_2;
    QGroupBox *groupBox_2;
    QLabel *label_12;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLineEdit *txtProjectName;
    QComboBox *cbDepartment_2;
    QLineEdit *txtProjectCode;
    QComboBox *cbStartingMonth;
    QTextEdit *txtDescription;
    QGroupBox *tcCEOProject;
    QTabWidget *tabWidget;
    QWidget *tbAssigedProjects;
    QPushButton *btnStartProjcet;
    QTableView *dgAssignedProjects;
    QWidget *tbCurrentProject;
    QPushButton *btnCompleteProject;
    QTableView *dgCurrentProjects;
    QWidget *tbCompletedProjects;
    QTableView *dgCompletedProjects;
    QLabel *label_22;
    QPushButton *btnManageProjects_2;

    void setupUi(QDialog *ceohomescreen)
    {
        if (ceohomescreen->objectName().isEmpty())
            ceohomescreen->setObjectName(QString::fromUtf8("ceohomescreen"));
        ceohomescreen->resize(1505, 810);
        btnManageProjectsCEO = new QPushButton(ceohomescreen);
        btnManageProjectsCEO->setObjectName(QString::fromUtf8("btnManageProjectsCEO"));
        btnManageProjectsCEO->setGeometry(QRect(890, 40, 171, 48));
        btnHomeCEO = new QPushButton(ceohomescreen);
        btnHomeCEO->setObjectName(QString::fromUtf8("btnHomeCEO"));
        btnHomeCEO->setGeometry(QRect(420, 40, 201, 48));
        button1 = new QPushButton(ceohomescreen);
        button1->setObjectName(QString::fromUtf8("button1"));
        button1->setGeometry(QRect(1100, 40, 151, 48));
        button1->setFlat(false);
        btnManageEmpCEO = new QPushButton(ceohomescreen);
        btnManageEmpCEO->setObjectName(QString::fromUtf8("btnManageEmpCEO"));
        btnManageEmpCEO->setGeometry(QRect(650, 40, 201, 48));
        homeControlCEO = new QGroupBox(ceohomescreen);
        homeControlCEO->setObjectName(QString::fromUtf8("homeControlCEO"));
        homeControlCEO->setGeometry(QRect(150, 100, 1211, 681));
        homeControlCEO->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label = new QLabel(homeControlCEO);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(0, 0, 1161, 61));
        QFont font;
        font.setPointSize(18);
        label->setFont(font);
        label->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label->setFrameShape(QFrame::Panel);
        label->setTextFormat(Qt::AutoText);
        label->setAlignment(Qt::AlignCenter);
        label->setWordWrap(false);
        label_4 = new QLabel(homeControlCEO);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(200, 80, 73, 67));
        label_4->setFrameShape(QFrame::StyledPanel);
        label_4->setAlignment(Qt::AlignCenter);
        frame = new QFrame(homeControlCEO);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(179, 107, 219, 68));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Plain);
        label_7 = new QLabel(frame);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(120, 10, 81, 16));
        QFont font1;
        font1.setPointSize(9);
        label_7->setFont(font1);
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(121, 121, 121);"));
        lblNotStartedCount_3 = new QLabel(frame);
        lblNotStartedCount_3->setObjectName(QString::fromUtf8("lblNotStartedCount_3"));
        lblNotStartedCount_3->setGeometry(QRect(170, 30, 31, 27));
        QFont font2;
        font2.setPointSize(13);
        font2.setBold(true);
        font2.setWeight(75);
        lblNotStartedCount_3->setFont(font2);
        lblNotStartedCount_3->setStyleSheet(QString::fromUtf8("color:\"black\""));
        lblNotStartedCount_3->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(homeControlCEO);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(480, 80, 73, 67));
        label_8->setFrameShape(QFrame::StyledPanel);
        label_8->setAlignment(Qt::AlignCenter);
        frame_3 = new QFrame(homeControlCEO);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(464, 107, 219, 68));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Plain);
        label_13 = new QLabel(frame_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(120, 10, 81, 16));
        label_13->setFont(font1);
        label_13->setStyleSheet(QString::fromUtf8("color: rgb(121, 121, 121);"));
        lblInProgressCount_3 = new QLabel(frame_3);
        lblInProgressCount_3->setObjectName(QString::fromUtf8("lblInProgressCount_3"));
        lblInProgressCount_3->setGeometry(QRect(170, 30, 31, 27));
        lblInProgressCount_3->setFont(font2);
        lblInProgressCount_3->setStyleSheet(QString::fromUtf8("color:\"black\""));
        lblInProgressCount_3->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(homeControlCEO);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(754, 107, 219, 68));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Plain);
        label_14 = new QLabel(frame_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(120, 10, 81, 16));
        label_14->setFont(font1);
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(121, 121, 121);"));
        lblCompletedCount_3 = new QLabel(frame_2);
        lblCompletedCount_3->setObjectName(QString::fromUtf8("lblCompletedCount_3"));
        lblCompletedCount_3->setGeometry(QRect(170, 30, 31, 27));
        lblCompletedCount_3->setFont(font2);
        lblCompletedCount_3->setStyleSheet(QString::fromUtf8("color:\"black\""));
        lblCompletedCount_3->setAlignment(Qt::AlignCenter);
        frame_4 = new QFrame(homeControlCEO);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(179, 320, 794, 332));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Plain);
        frame_4->setLineWidth(0);
        lblNameHeader_3 = new QLabel(frame_4);
        lblNameHeader_3->setObjectName(QString::fromUtf8("lblNameHeader_3"));
        lblNameHeader_3->setGeometry(QRect(247, 20, 163, 35));
        QFont font3;
        font3.setPointSize(16);
        lblNameHeader_3->setFont(font3);
        lblNameHeader_3->setAutoFillBackground(false);
        lblNameHeader_3->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        lblNameHeader_3->setFrameShadow(QFrame::Sunken);
        lblNameHeader_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblRoleHeader_3 = new QLabel(frame_4);
        lblRoleHeader_3->setObjectName(QString::fromUtf8("lblRoleHeader_3"));
        lblRoleHeader_3->setGeometry(QRect(247, 60, 84, 24));
        QFont font4;
        font4.setPointSize(12);
        lblRoleHeader_3->setFont(font4);
        lblRoleHeader_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        line_3 = new QFrame(frame_4);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(220, 90, 571, 16));
        line_3->setFont(font4);
        line_3->setStyleSheet(QString::fromUtf8(""));
        line_3->setFrameShadow(QFrame::Sunken);
        line_3->setLineWidth(4);
        line_3->setMidLineWidth(0);
        line_3->setFrameShape(QFrame::HLine);
        splitter_3 = new QSplitter(frame_4);
        splitter_3->setObjectName(QString::fromUtf8("splitter_3"));
        splitter_3->setGeometry(QRect(250, 130, 171, 181));
        splitter_3->setOrientation(Qt::Vertical);
        lblName_3 = new QLabel(splitter_3);
        lblName_3->setObjectName(QString::fromUtf8("lblName_3"));
        QFont font5;
        font5.setPointSize(10);
        lblName_3->setFont(font5);
        lblName_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblName_3);
        lblGender_3 = new QLabel(splitter_3);
        lblGender_3->setObjectName(QString::fromUtf8("lblGender_3"));
        lblGender_3->setFont(font5);
        lblGender_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblGender_3);
        lblAddress_3 = new QLabel(splitter_3);
        lblAddress_3->setObjectName(QString::fromUtf8("lblAddress_3"));
        lblAddress_3->setFont(font5);
        lblAddress_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblAddress_3);
        lblDepartment_3 = new QLabel(splitter_3);
        lblDepartment_3->setObjectName(QString::fromUtf8("lblDepartment_3"));
        lblDepartment_3->setFont(font5);
        lblDepartment_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblDepartment_3);
        lblRole_3 = new QLabel(splitter_3);
        lblRole_3->setObjectName(QString::fromUtf8("lblRole_3"));
        lblRole_3->setFont(font5);
        lblRole_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblRole_3);
        lblUsername_3 = new QLabel(splitter_3);
        lblUsername_3->setObjectName(QString::fromUtf8("lblUsername_3"));
        lblUsername_3->setFont(font5);
        lblUsername_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblUsername_3);
        label_15 = new QLabel(homeControlCEO);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(770, 80, 73, 67));
        label_15->setFrameShape(QFrame::StyledPanel);
        label_15->setAlignment(Qt::AlignCenter);
        pUserAvatar = new QLabel(homeControlCEO);
        pUserAvatar->setObjectName(QString::fromUtf8("pUserAvatar"));
        pUserAvatar->setGeometry(QRect(200, 240, 193, 182));
        pUserAvatar->setFrameShape(QFrame::StyledPanel);
        pUserAvatar->setAlignment(Qt::AlignCenter);
        label->raise();
        frame->raise();
        frame_3->raise();
        frame_2->raise();
        frame_4->raise();
        label_15->raise();
        pUserAvatar->raise();
        label_4->raise();
        label_8->raise();
        ucManageEmployeeControl = new QGroupBox(ceohomescreen);
        ucManageEmployeeControl->setObjectName(QString::fromUtf8("ucManageEmployeeControl"));
        ucManageEmployeeControl->setGeometry(QRect(110, 100, 1211, 681));
        ucManageEmployeeControl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        btnEditEmployee = new QPushButton(ucManageEmployeeControl);
        btnEditEmployee->setObjectName(QString::fromUtf8("btnEditEmployee"));
        btnEditEmployee->setGeometry(QRect(222, 570, 163, 35));
        btnEditEmployee->setStyleSheet(QString::fromUtf8("color:\"black\";"));
        label_16 = new QLabel(ucManageEmployeeControl);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(0, 0, 1161, 61));
        label_16->setFont(font);
        label_16->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setTextFormat(Qt::AutoText);
        label_16->setAlignment(Qt::AlignCenter);
        label_16->setWordWrap(false);
        btnDeleteEmployee = new QPushButton(ucManageEmployeeControl);
        btnDeleteEmployee->setObjectName(QString::fromUtf8("btnDeleteEmployee"));
        btnDeleteEmployee->setGeometry(QRect(30, 630, 164, 35));
        btnDeleteEmployee->setStyleSheet(QString::fromUtf8("color:\"black\";"));
        dgEmployee = new QTableView(ucManageEmployeeControl);
        dgEmployee->setObjectName(QString::fromUtf8("dgEmployee"));
        dgEmployee->setGeometry(QRect(600, 70, 601, 581));
        dgEmployee->setHorizontalScrollMode(QAbstractItemView::ScrollPerPixel);
        dgEmployee->setShowGrid(true);
        dgEmployee->setSortingEnabled(false);
        dgEmployee->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        dgEmployee->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
        btnAddEmployee = new QPushButton(ucManageEmployeeControl);
        btnAddEmployee->setObjectName(QString::fromUtf8("btnAddEmployee"));
        btnAddEmployee->setGeometry(QRect(30, 570, 164, 35));
        btnAddEmployee->setStyleSheet(QString::fromUtf8("color:\"black\";"));
        groupBox = new QGroupBox(ucManageEmployeeControl);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(1, 60, 591, 481));
        groupBox->setStyleSheet(QString::fromUtf8("color:\"black\";"));
        txtEmployeeName = new QLineEdit(groupBox);
        txtEmployeeName->setObjectName(QString::fromUtf8("txtEmployeeName"));
        txtEmployeeName->setGeometry(QRect(160, 33, 418, 24));
        txtPassword = new QLineEdit(groupBox);
        txtPassword->setObjectName(QString::fromUtf8("txtPassword"));
        txtPassword->setGeometry(QRect(160, 440, 418, 24));
        cbUserRole = new QComboBox(groupBox);
        cbUserRole->setObjectName(QString::fromUtf8("cbUserRole"));
        cbUserRole->setGeometry(QRect(160, 320, 254, 24));
        cbDepartment = new QComboBox(groupBox);
        cbDepartment->setObjectName(QString::fromUtf8("cbDepartment"));
        cbDepartment->setGeometry(QRect(160, 260, 254, 24));
        cbGender = new QComboBox(groupBox);
        cbGender->setObjectName(QString::fromUtf8("cbGender"));
        cbGender->setGeometry(QRect(160, 200, 254, 24));
        txtUsername = new QLineEdit(groupBox);
        txtUsername->setObjectName(QString::fromUtf8("txtUsername"));
        txtUsername->setGeometry(QRect(160, 380, 418, 24));
        txtAddress = new QTextEdit(groupBox);
        txtAddress->setObjectName(QString::fromUtf8("txtAddress"));
        txtAddress->setGeometry(QRect(160, 85, 418, 85));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(12, 440, 92, 30));
        label_9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(12, 85, 92, 30));
        label_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(12, 260, 92, 30));
        label_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(12, 320, 92, 30));
        label_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(12, 200, 92, 30));
        label_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(12, 380, 92, 30));
        label_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(12, 33, 92, 30));
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        btnLoad = new QPushButton(ucManageEmployeeControl);
        btnLoad->setObjectName(QString::fromUtf8("btnLoad"));
        btnLoad->setGeometry(QRect(210, 630, 164, 35));
        btnLoad->setStyleSheet(QString::fromUtf8("color:\"black\";"));
        usManageProjectControl = new QGroupBox(ceohomescreen);
        usManageProjectControl->setObjectName(QString::fromUtf8("usManageProjectControl"));
        usManageProjectControl->setGeometry(QRect(20, 120, 1461, 631));
        usManageProjectControl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        dgProject_2 = new QTableView(usManageProjectControl);
        dgProject_2->setObjectName(QString::fromUtf8("dgProject_2"));
        dgProject_2->setGeometry(QRect(650, 80, 791, 511));
        btnEditProject_2 = new QPushButton(usManageProjectControl);
        btnEditProject_2->setObjectName(QString::fromUtf8("btnEditProject_2"));
        btnEditProject_2->setGeometry(QRect(167, 580, 121, 35));
        btnEditProject_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        btnDeleteProject_2 = new QPushButton(usManageProjectControl);
        btnDeleteProject_2->setObjectName(QString::fromUtf8("btnDeleteProject_2"));
        btnDeleteProject_2->setGeometry(QRect(293, 580, 122, 35));
        btnDeleteProject_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        label_17 = new QLabel(usManageProjectControl);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(260, 10, 1161, 61));
        label_17->setFont(font);
        label_17->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setTextFormat(Qt::AutoText);
        label_17->setAlignment(Qt::AlignCenter);
        label_17->setWordWrap(false);
        btnAddProject_2 = new QPushButton(usManageProjectControl);
        btnAddProject_2->setObjectName(QString::fromUtf8("btnAddProject_2"));
        btnAddProject_2->setGeometry(QRect(40, 580, 122, 35));
        btnAddProject_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        btnAssignUser_2 = new QPushButton(usManageProjectControl);
        btnAssignUser_2->setObjectName(QString::fromUtf8("btnAssignUser_2"));
        btnAssignUser_2->setGeometry(QRect(420, 580, 121, 35));
        btnAssignUser_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        groupBox_2 = new QGroupBox(usManageProjectControl);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 70, 621, 458));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(6, 110, 91, 16));
        label_12->setStyleSheet(QString::fromUtf8("color: \"black\""));
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(6, 280, 91, 16));
        label_18->setStyleSheet(QString::fromUtf8("color: \"black\""));
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(6, 200, 55, 16));
        label_19->setStyleSheet(QString::fromUtf8("color: \"black\""));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(6, 350, 55, 16));
        label_20->setStyleSheet(QString::fromUtf8("color: \"black\""));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(6, 50, 111, 16));
        label_21->setStyleSheet(QString::fromUtf8("color: \"black\""));
        txtProjectName = new QLineEdit(groupBox_2);
        txtProjectName->setObjectName(QString::fromUtf8("txtProjectName"));
        txtProjectName->setGeometry(QRect(130, 100, 478, 24));
        cbDepartment_2 = new QComboBox(groupBox_2);
        cbDepartment_2->setObjectName(QString::fromUtf8("cbDepartment_2"));
        cbDepartment_2->setGeometry(QRect(130, 350, 245, 24));
        txtProjectCode = new QLineEdit(groupBox_2);
        txtProjectCode->setObjectName(QString::fromUtf8("txtProjectCode"));
        txtProjectCode->setGeometry(QRect(130, 50, 478, 24));
        cbStartingMonth = new QComboBox(groupBox_2);
        cbStartingMonth->setObjectName(QString::fromUtf8("cbStartingMonth"));
        cbStartingMonth->setGeometry(QRect(130, 280, 245, 24));
        txtDescription = new QTextEdit(groupBox_2);
        txtDescription->setObjectName(QString::fromUtf8("txtDescription"));
        txtDescription->setGeometry(QRect(130, 160, 478, 96));
        tcCEOProject = new QGroupBox(ceohomescreen);
        tcCEOProject->setObjectName(QString::fromUtf8("tcCEOProject"));
        tcCEOProject->setGeometry(QRect(80, 100, 1170, 682));
        tcCEOProject->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        tabWidget = new QTabWidget(tcCEOProject);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(9, 70, 1151, 601));
        tabWidget->setStyleSheet(QString::fromUtf8("color:\"black\""));
        tbAssigedProjects = new QWidget();
        tbAssigedProjects->setObjectName(QString::fromUtf8("tbAssigedProjects"));
        btnStartProjcet = new QPushButton(tbAssigedProjects);
        btnStartProjcet->setObjectName(QString::fromUtf8("btnStartProjcet"));
        btnStartProjcet->setGeometry(QRect(870, 514, 141, 41));
        btnStartProjcet->setStyleSheet(QString::fromUtf8("color:\"black\";"));
        dgAssignedProjects = new QTableView(tbAssigedProjects);
        dgAssignedProjects->setObjectName(QString::fromUtf8("dgAssignedProjects"));
        dgAssignedProjects->setGeometry(QRect(20, 50, 1091, 421));
        tabWidget->addTab(tbAssigedProjects, QString());
        tbCurrentProject = new QWidget();
        tbCurrentProject->setObjectName(QString::fromUtf8("tbCurrentProject"));
        btnCompleteProject = new QPushButton(tbCurrentProject);
        btnCompleteProject->setObjectName(QString::fromUtf8("btnCompleteProject"));
        btnCompleteProject->setGeometry(QRect(889, 514, 161, 41));
        dgCurrentProjects = new QTableView(tbCurrentProject);
        dgCurrentProjects->setObjectName(QString::fromUtf8("dgCurrentProjects"));
        dgCurrentProjects->setGeometry(QRect(30, 20, 1091, 461));
        tabWidget->addTab(tbCurrentProject, QString());
        tbCompletedProjects = new QWidget();
        tbCompletedProjects->setObjectName(QString::fromUtf8("tbCompletedProjects"));
        dgCompletedProjects = new QTableView(tbCompletedProjects);
        dgCompletedProjects->setObjectName(QString::fromUtf8("dgCompletedProjects"));
        dgCompletedProjects->setGeometry(QRect(10, 10, 1131, 501));
        tabWidget->addTab(tbCompletedProjects, QString());
        label_22 = new QLabel(tcCEOProject);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(0, 0, 1170, 61));
        label_22->setFont(font);
        label_22->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label_22->setFrameShape(QFrame::Panel);
        label_22->setTextFormat(Qt::AutoText);
        label_22->setAlignment(Qt::AlignCenter);
        label_22->setWordWrap(false);
        btnManageProjects_2 = new QPushButton(ceohomescreen);
        btnManageProjects_2->setObjectName(QString::fromUtf8("btnManageProjects_2"));
        btnManageProjects_2->setGeometry(QRect(110, 20, 269, 48));
        btnManageProjectsCEO->raise();
        btnHomeCEO->raise();
        button1->raise();
        btnManageEmpCEO->raise();
        homeControlCEO->raise();
        usManageProjectControl->raise();
        tcCEOProject->raise();
        btnManageProjects_2->raise();
        ucManageEmployeeControl->raise();

        retranslateUi(ceohomescreen);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(ceohomescreen);
    } // setupUi

    void retranslateUi(QDialog *ceohomescreen)
    {
        ceohomescreen->setWindowTitle(QCoreApplication::translate("ceohomescreen", "Dialog", nullptr));
        btnManageProjectsCEO->setText(QCoreApplication::translate("ceohomescreen", "Manage Projects", nullptr));
        btnHomeCEO->setText(QCoreApplication::translate("ceohomescreen", "Home", nullptr));
        button1->setText(QCoreApplication::translate("ceohomescreen", "Log Out", nullptr));
        btnManageEmpCEO->setText(QCoreApplication::translate("ceohomescreen", "Manage Employees", nullptr));
        homeControlCEO->setTitle(QString());
        label->setText(QCoreApplication::translate("ceohomescreen", "Welcome to Work Mate", nullptr));
        label_4->setText(QCoreApplication::translate("ceohomescreen", "TextLabel", nullptr));
        label_7->setText(QCoreApplication::translate("ceohomescreen", "Not Started", nullptr));
        lblNotStartedCount_3->setText(QCoreApplication::translate("ceohomescreen", "5", nullptr));
        label_8->setText(QCoreApplication::translate("ceohomescreen", "TextLabel", nullptr));
        label_13->setText(QCoreApplication::translate("ceohomescreen", "In Progress", nullptr));
        lblInProgressCount_3->setText(QCoreApplication::translate("ceohomescreen", "5", nullptr));
        label_14->setText(QCoreApplication::translate("ceohomescreen", "Completed", nullptr));
        lblCompletedCount_3->setText(QCoreApplication::translate("ceohomescreen", "5", nullptr));
        lblNameHeader_3->setText(QCoreApplication::translate("ceohomescreen", "David Mosby", nullptr));
        lblRoleHeader_3->setText(QCoreApplication::translate("ceohomescreen", "Manager", nullptr));
        lblName_3->setText(QCoreApplication::translate("ceohomescreen", "David Mosby", nullptr));
        lblGender_3->setText(QCoreApplication::translate("ceohomescreen", "Male", nullptr));
        lblAddress_3->setText(QCoreApplication::translate("ceohomescreen", "Lacinia Road, Lacinia ", nullptr));
        lblDepartment_3->setText(QCoreApplication::translate("ceohomescreen", "Finance Department", nullptr));
        lblRole_3->setText(QCoreApplication::translate("ceohomescreen", "Manager", nullptr));
        lblUsername_3->setText(QCoreApplication::translate("ceohomescreen", "SandaruK", nullptr));
        label_15->setText(QCoreApplication::translate("ceohomescreen", "TextLabel", nullptr));
        pUserAvatar->setText(QCoreApplication::translate("ceohomescreen", "TextLabel", nullptr));
        ucManageEmployeeControl->setTitle(QString());
        btnEditEmployee->setText(QCoreApplication::translate("ceohomescreen", "Update", nullptr));
        label_16->setText(QCoreApplication::translate("ceohomescreen", "Employee Details", nullptr));
        btnDeleteEmployee->setText(QCoreApplication::translate("ceohomescreen", "Delete", nullptr));
        btnAddEmployee->setText(QCoreApplication::translate("ceohomescreen", "Add", nullptr));
        groupBox->setTitle(QString());
        label_9->setText(QCoreApplication::translate("ceohomescreen", "Password", nullptr));
        label_2->setText(QCoreApplication::translate("ceohomescreen", "Address", nullptr));
        label_5->setText(QCoreApplication::translate("ceohomescreen", "Department", nullptr));
        label_6->setText(QCoreApplication::translate("ceohomescreen", "User Role", nullptr));
        label_3->setText(QCoreApplication::translate("ceohomescreen", "Gender", nullptr));
        label_10->setText(QCoreApplication::translate("ceohomescreen", "Username", nullptr));
        label_11->setText(QCoreApplication::translate("ceohomescreen", "Employee Name", nullptr));
        btnLoad->setText(QCoreApplication::translate("ceohomescreen", "Load", nullptr));
        usManageProjectControl->setTitle(QString());
        btnEditProject_2->setText(QCoreApplication::translate("ceohomescreen", "Edit", nullptr));
        btnDeleteProject_2->setText(QCoreApplication::translate("ceohomescreen", "Delete", nullptr));
        label_17->setText(QCoreApplication::translate("ceohomescreen", "Project Details", nullptr));
        btnAddProject_2->setText(QCoreApplication::translate("ceohomescreen", "Add", nullptr));
        btnAssignUser_2->setText(QCoreApplication::translate("ceohomescreen", "Assign User", nullptr));
        groupBox_2->setTitle(QString());
        label_12->setText(QCoreApplication::translate("ceohomescreen", "Project Name", nullptr));
        label_18->setText(QCoreApplication::translate("ceohomescreen", "Starting Month", nullptr));
        label_19->setText(QCoreApplication::translate("ceohomescreen", "Description", nullptr));
        label_20->setText(QCoreApplication::translate("ceohomescreen", "Department", nullptr));
        label_21->setText(QCoreApplication::translate("ceohomescreen", "Project Code", nullptr));
        tcCEOProject->setTitle(QString());
        btnStartProjcet->setText(QCoreApplication::translate("ceohomescreen", "Start Project", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tbAssigedProjects), QCoreApplication::translate("ceohomescreen", "Assigned Porjects", nullptr));
        btnCompleteProject->setText(QCoreApplication::translate("ceohomescreen", "Complete Project", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tbCurrentProject), QCoreApplication::translate("ceohomescreen", "Projects Inprogress", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tbCompletedProjects), QCoreApplication::translate("ceohomescreen", "Completed Projects", nullptr));
        label_22->setText(QCoreApplication::translate("ceohomescreen", "Project Details", nullptr));
        btnManageProjects_2->setText(QCoreApplication::translate("ceohomescreen", "My Projects", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ceohomescreen: public Ui_ceohomescreen {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CEOHOMESCREEN_H
