/********************************************************************************
** Form generated from reading UI file 'managerhomescreen.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MANAGERHOMESCREEN_H
#define UI_MANAGERHOMESCREEN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_managerhomescreen
{
public:
    QPushButton *btnManageProjects;
    QPushButton *btnHome;
    QPushButton *btnLogout;
    QPushButton *btnManageEmp;
    QGroupBox *manageProjectControl;
    QTableView *dgProject_2;
    QPushButton *btnEditProject_2;
    QPushButton *btnDeleteProject_2;
    QLabel *label_17;
    QPushButton *btnAddProject_2;
    QPushButton *btnAssignUser_2;
    QGroupBox *groupBox_2;
    QLabel *label_12;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *txtProjectName;
    QComboBox *cbDepartment_2;
    QLineEdit *txtProjectCode;
    QComboBox *cbStartingMonth;
    QTextEdit *txtDescription;
    QGroupBox *manageEmployeeControl;
    QPushButton *btnEditEmployee_2;
    QLabel *label_18;
    QPushButton *btnDeleteEmployee_2;
    QTableView *dgEmployee_2;
    QPushButton *btnAddEmployee_2;
    QGroupBox *groupBox;
    QLineEdit *txtEmployeeName;
    QLineEdit *txtPassword;
    QComboBox *cbUserRole;
    QComboBox *cbDepartment;
    QComboBox *cbGender;
    QLineEdit *txtUsername;
    QTextEdit *txtAddress;
    QLabel *label_9;
    QLabel *label_2;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_3;
    QLabel *label_10;
    QLabel *label_11;
    QGroupBox *homeControlManager;
    QLabel *label;
    QLabel *label_4;
    QFrame *frame;
    QLabel *label_7;
    QLabel *lblNotStartedCount_3;
    QLabel *label_8;
    QFrame *frame_3;
    QLabel *label_13;
    QLabel *lblInProgressCount_3;
    QFrame *frame_2;
    QLabel *label_14;
    QLabel *lblCompletedCount_3;
    QFrame *frame_4;
    QLabel *lblNameHeader_3;
    QLabel *lblRoleHeader_3;
    QFrame *line_3;
    QSplitter *splitter_3;
    QLabel *lblName_3;
    QLabel *lblGender_3;
    QLabel *lblAddress_3;
    QLabel *lblDepartment_3;
    QLabel *lblRole_3;
    QLabel *lblUsername_3;
    QLabel *label_15;
    QLabel *pUserAvatar;
    QGroupBox *tcManagerProject;
    QTabWidget *tabWidget;
    QWidget *tbAssigedProjects;
    QPushButton *btnStartProjcet;
    QTableView *dgAssignedProjects;
    QWidget *tbCurrentProject;
    QPushButton *btnCompleteProject;
    QTableView *dgCurrentProjects;
    QWidget *tbCompletedProjects;
    QTableView *dgCompletedProjects;
    QLabel *label_16;
    QPushButton *btnManageProjects_2;

    void setupUi(QDialog *managerhomescreen)
    {
        if (managerhomescreen->objectName().isEmpty())
            managerhomescreen->setObjectName(QString::fromUtf8("managerhomescreen"));
        managerhomescreen->resize(1439, 869);
        btnManageProjects = new QPushButton(managerhomescreen);
        btnManageProjects->setObjectName(QString::fromUtf8("btnManageProjects"));
        btnManageProjects->setGeometry(QRect(870, 50, 269, 48));
        btnHome = new QPushButton(managerhomescreen);
        btnHome->setObjectName(QString::fromUtf8("btnHome"));
        btnHome->setGeometry(QRect(290, 60, 269, 48));
        btnLogout = new QPushButton(managerhomescreen);
        btnLogout->setObjectName(QString::fromUtf8("btnLogout"));
        btnLogout->setGeometry(QRect(1160, 50, 269, 48));
        btnLogout->setFlat(false);
        btnManageEmp = new QPushButton(managerhomescreen);
        btnManageEmp->setObjectName(QString::fromUtf8("btnManageEmp"));
        btnManageEmp->setGeometry(QRect(570, 50, 269, 48));
        manageProjectControl = new QGroupBox(managerhomescreen);
        manageProjectControl->setObjectName(QString::fromUtf8("manageProjectControl"));
        manageProjectControl->setGeometry(QRect(9, 150, 1421, 682));
        manageProjectControl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        dgProject_2 = new QTableView(manageProjectControl);
        dgProject_2->setObjectName(QString::fromUtf8("dgProject_2"));
        dgProject_2->setGeometry(QRect(697, 80, 721, 521));
        btnEditProject_2 = new QPushButton(manageProjectControl);
        btnEditProject_2->setObjectName(QString::fromUtf8("btnEditProject_2"));
        btnEditProject_2->setGeometry(QRect(147, 630, 121, 35));
        btnEditProject_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        btnDeleteProject_2 = new QPushButton(manageProjectControl);
        btnDeleteProject_2->setObjectName(QString::fromUtf8("btnDeleteProject_2"));
        btnDeleteProject_2->setGeometry(QRect(273, 630, 122, 35));
        btnDeleteProject_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        label_17 = new QLabel(manageProjectControl);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(260, 10, 1161, 61));
        QFont font;
        font.setPointSize(18);
        label_17->setFont(font);
        label_17->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label_17->setFrameShape(QFrame::Panel);
        label_17->setTextFormat(Qt::AutoText);
        label_17->setAlignment(Qt::AlignCenter);
        label_17->setWordWrap(false);
        btnAddProject_2 = new QPushButton(manageProjectControl);
        btnAddProject_2->setObjectName(QString::fromUtf8("btnAddProject_2"));
        btnAddProject_2->setGeometry(QRect(20, 630, 122, 35));
        btnAddProject_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        btnAssignUser_2 = new QPushButton(manageProjectControl);
        btnAssignUser_2->setObjectName(QString::fromUtf8("btnAssignUser_2"));
        btnAssignUser_2->setGeometry(QRect(400, 630, 121, 35));
        btnAssignUser_2->setStyleSheet(QString::fromUtf8("color:\"black\""));
        groupBox_2 = new QGroupBox(manageProjectControl);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 80, 621, 458));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(6, 110, 91, 16));
        label_12->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(6, 280, 91, 16));
        label_19->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(6, 200, 55, 16));
        label_20->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(6, 350, 55, 16));
        label_21->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(6, 50, 111, 16));
        label_22->setStyleSheet(QString::fromUtf8("color:'black'"));
        txtProjectName = new QLineEdit(groupBox_2);
        txtProjectName->setObjectName(QString::fromUtf8("txtProjectName"));
        txtProjectName->setGeometry(QRect(130, 100, 478, 24));
        cbDepartment_2 = new QComboBox(groupBox_2);
        cbDepartment_2->setObjectName(QString::fromUtf8("cbDepartment_2"));
        cbDepartment_2->setGeometry(QRect(130, 350, 245, 24));
        txtProjectCode = new QLineEdit(groupBox_2);
        txtProjectCode->setObjectName(QString::fromUtf8("txtProjectCode"));
        txtProjectCode->setGeometry(QRect(130, 50, 478, 24));
        cbStartingMonth = new QComboBox(groupBox_2);
        cbStartingMonth->setObjectName(QString::fromUtf8("cbStartingMonth"));
        cbStartingMonth->setGeometry(QRect(130, 280, 245, 24));
        txtDescription = new QTextEdit(groupBox_2);
        txtDescription->setObjectName(QString::fromUtf8("txtDescription"));
        txtDescription->setGeometry(QRect(130, 160, 478, 96));
        manageEmployeeControl = new QGroupBox(managerhomescreen);
        manageEmployeeControl->setObjectName(QString::fromUtf8("manageEmployeeControl"));
        manageEmployeeControl->setGeometry(QRect(10, 140, 1421, 682));
        manageEmployeeControl->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        btnEditEmployee_2 = new QPushButton(manageEmployeeControl);
        btnEditEmployee_2->setObjectName(QString::fromUtf8("btnEditEmployee_2"));
        btnEditEmployee_2->setGeometry(QRect(222, 620, 163, 35));
        btnEditEmployee_2->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_18 = new QLabel(manageEmployeeControl);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(250, 10, 1161, 61));
        label_18->setFont(font);
        label_18->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label_18->setFrameShape(QFrame::Panel);
        label_18->setTextFormat(Qt::AutoText);
        label_18->setAlignment(Qt::AlignCenter);
        label_18->setWordWrap(false);
        btnDeleteEmployee_2 = new QPushButton(manageEmployeeControl);
        btnDeleteEmployee_2->setObjectName(QString::fromUtf8("btnDeleteEmployee_2"));
        btnDeleteEmployee_2->setGeometry(QRect(390, 620, 164, 35));
        btnDeleteEmployee_2->setStyleSheet(QString::fromUtf8("color:'black'"));
        dgEmployee_2 = new QTableView(manageEmployeeControl);
        dgEmployee_2->setObjectName(QString::fromUtf8("dgEmployee_2"));
        dgEmployee_2->setGeometry(QRect(617, 80, 801, 521));
        btnAddEmployee_2 = new QPushButton(manageEmployeeControl);
        btnAddEmployee_2->setObjectName(QString::fromUtf8("btnAddEmployee_2"));
        btnAddEmployee_2->setGeometry(QRect(53, 620, 164, 35));
        btnAddEmployee_2->setStyleSheet(QString::fromUtf8("color:'black'"));
        groupBox = new QGroupBox(manageEmployeeControl);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 90, 591, 511));
        txtEmployeeName = new QLineEdit(groupBox);
        txtEmployeeName->setObjectName(QString::fromUtf8("txtEmployeeName"));
        txtEmployeeName->setGeometry(QRect(160, 33, 418, 24));
        txtPassword = new QLineEdit(groupBox);
        txtPassword->setObjectName(QString::fromUtf8("txtPassword"));
        txtPassword->setGeometry(QRect(160, 440, 418, 24));
        cbUserRole = new QComboBox(groupBox);
        cbUserRole->setObjectName(QString::fromUtf8("cbUserRole"));
        cbUserRole->setGeometry(QRect(160, 320, 254, 24));
        cbDepartment = new QComboBox(groupBox);
        cbDepartment->setObjectName(QString::fromUtf8("cbDepartment"));
        cbDepartment->setGeometry(QRect(160, 260, 254, 24));
        cbGender = new QComboBox(groupBox);
        cbGender->setObjectName(QString::fromUtf8("cbGender"));
        cbGender->setGeometry(QRect(160, 200, 254, 24));
        txtUsername = new QLineEdit(groupBox);
        txtUsername->setObjectName(QString::fromUtf8("txtUsername"));
        txtUsername->setGeometry(QRect(160, 380, 418, 24));
        txtAddress = new QTextEdit(groupBox);
        txtAddress->setObjectName(QString::fromUtf8("txtAddress"));
        txtAddress->setGeometry(QRect(160, 85, 418, 85));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(12, 440, 92, 30));
        label_9->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(12, 85, 92, 30));
        label_2->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(12, 260, 92, 30));
        label_5->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(12, 320, 92, 30));
        label_6->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(12, 200, 92, 30));
        label_3->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(12, 380, 92, 30));
        label_10->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(12, 33, 92, 30));
        label_11->setStyleSheet(QString::fromUtf8("color:'black'"));
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        homeControlManager = new QGroupBox(managerhomescreen);
        homeControlManager->setObjectName(QString::fromUtf8("homeControlManager"));
        homeControlManager->setGeometry(QRect(240, 120, 1170, 682));
        homeControlManager->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        label = new QLabel(homeControlManager);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(0, 0, 1161, 61));
        label->setFont(font);
        label->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label->setFrameShape(QFrame::Panel);
        label->setTextFormat(Qt::AutoText);
        label->setAlignment(Qt::AlignCenter);
        label->setWordWrap(false);
        label_4 = new QLabel(homeControlManager);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(200, 80, 73, 67));
        label_4->setFrameShape(QFrame::StyledPanel);
        label_4->setAlignment(Qt::AlignCenter);
        frame = new QFrame(homeControlManager);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(179, 107, 219, 68));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Plain);
        label_7 = new QLabel(frame);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(120, 10, 81, 16));
        QFont font1;
        font1.setPointSize(9);
        label_7->setFont(font1);
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(121, 121, 121);"));
        lblNotStartedCount_3 = new QLabel(frame);
        lblNotStartedCount_3->setObjectName(QString::fromUtf8("lblNotStartedCount_3"));
        lblNotStartedCount_3->setGeometry(QRect(170, 30, 31, 27));
        QFont font2;
        font2.setPointSize(13);
        font2.setBold(true);
        font2.setWeight(75);
        lblNotStartedCount_3->setFont(font2);
        lblNotStartedCount_3->setStyleSheet(QString::fromUtf8("color:\"black\""));
        lblNotStartedCount_3->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(homeControlManager);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(480, 80, 73, 67));
        label_8->setFrameShape(QFrame::StyledPanel);
        label_8->setAlignment(Qt::AlignCenter);
        frame_3 = new QFrame(homeControlManager);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(464, 107, 219, 68));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Plain);
        label_13 = new QLabel(frame_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(120, 10, 81, 16));
        label_13->setFont(font1);
        label_13->setStyleSheet(QString::fromUtf8("color: rgb(121, 121, 121);"));
        lblInProgressCount_3 = new QLabel(frame_3);
        lblInProgressCount_3->setObjectName(QString::fromUtf8("lblInProgressCount_3"));
        lblInProgressCount_3->setGeometry(QRect(170, 30, 31, 27));
        lblInProgressCount_3->setFont(font2);
        lblInProgressCount_3->setStyleSheet(QString::fromUtf8("color:\"black\""));
        lblInProgressCount_3->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(homeControlManager);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(754, 107, 219, 68));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Plain);
        label_14 = new QLabel(frame_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(120, 10, 81, 16));
        label_14->setFont(font1);
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(121, 121, 121);"));
        lblCompletedCount_3 = new QLabel(frame_2);
        lblCompletedCount_3->setObjectName(QString::fromUtf8("lblCompletedCount_3"));
        lblCompletedCount_3->setGeometry(QRect(170, 30, 31, 27));
        lblCompletedCount_3->setFont(font2);
        lblCompletedCount_3->setStyleSheet(QString::fromUtf8("color:\"black\""));
        lblCompletedCount_3->setAlignment(Qt::AlignCenter);
        frame_4 = new QFrame(homeControlManager);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(179, 320, 794, 332));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Plain);
        frame_4->setLineWidth(0);
        lblNameHeader_3 = new QLabel(frame_4);
        lblNameHeader_3->setObjectName(QString::fromUtf8("lblNameHeader_3"));
        lblNameHeader_3->setGeometry(QRect(247, 20, 163, 35));
        QFont font3;
        font3.setPointSize(16);
        lblNameHeader_3->setFont(font3);
        lblNameHeader_3->setAutoFillBackground(false);
        lblNameHeader_3->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);"));
        lblNameHeader_3->setFrameShadow(QFrame::Sunken);
        lblNameHeader_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblRoleHeader_3 = new QLabel(frame_4);
        lblRoleHeader_3->setObjectName(QString::fromUtf8("lblRoleHeader_3"));
        lblRoleHeader_3->setGeometry(QRect(247, 60, 84, 24));
        QFont font4;
        font4.setPointSize(12);
        lblRoleHeader_3->setFont(font4);
        lblRoleHeader_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        line_3 = new QFrame(frame_4);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(220, 90, 571, 16));
        line_3->setFont(font4);
        line_3->setStyleSheet(QString::fromUtf8(""));
        line_3->setFrameShadow(QFrame::Sunken);
        line_3->setLineWidth(4);
        line_3->setMidLineWidth(0);
        line_3->setFrameShape(QFrame::HLine);
        splitter_3 = new QSplitter(frame_4);
        splitter_3->setObjectName(QString::fromUtf8("splitter_3"));
        splitter_3->setGeometry(QRect(250, 130, 171, 181));
        splitter_3->setOrientation(Qt::Vertical);
        lblName_3 = new QLabel(splitter_3);
        lblName_3->setObjectName(QString::fromUtf8("lblName_3"));
        QFont font5;
        font5.setPointSize(10);
        lblName_3->setFont(font5);
        lblName_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblName_3);
        lblGender_3 = new QLabel(splitter_3);
        lblGender_3->setObjectName(QString::fromUtf8("lblGender_3"));
        lblGender_3->setFont(font5);
        lblGender_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblGender_3);
        lblAddress_3 = new QLabel(splitter_3);
        lblAddress_3->setObjectName(QString::fromUtf8("lblAddress_3"));
        lblAddress_3->setFont(font5);
        lblAddress_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblAddress_3);
        lblDepartment_3 = new QLabel(splitter_3);
        lblDepartment_3->setObjectName(QString::fromUtf8("lblDepartment_3"));
        lblDepartment_3->setFont(font5);
        lblDepartment_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblDepartment_3);
        lblRole_3 = new QLabel(splitter_3);
        lblRole_3->setObjectName(QString::fromUtf8("lblRole_3"));
        lblRole_3->setFont(font5);
        lblRole_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblRole_3);
        lblUsername_3 = new QLabel(splitter_3);
        lblUsername_3->setObjectName(QString::fromUtf8("lblUsername_3"));
        lblUsername_3->setFont(font5);
        lblUsername_3->setStyleSheet(QString::fromUtf8("color: rgb(91, 91, 91);"));
        splitter_3->addWidget(lblUsername_3);
        label_15 = new QLabel(homeControlManager);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(770, 80, 73, 67));
        label_15->setFrameShape(QFrame::StyledPanel);
        label_15->setAlignment(Qt::AlignCenter);
        pUserAvatar = new QLabel(homeControlManager);
        pUserAvatar->setObjectName(QString::fromUtf8("pUserAvatar"));
        pUserAvatar->setGeometry(QRect(200, 240, 193, 182));
        pUserAvatar->setFrameShape(QFrame::StyledPanel);
        pUserAvatar->setAlignment(Qt::AlignCenter);
        tcManagerProject = new QGroupBox(managerhomescreen);
        tcManagerProject->setObjectName(QString::fromUtf8("tcManagerProject"));
        tcManagerProject->setGeometry(QRect(50, 180, 1170, 682));
        tcManagerProject->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        tabWidget = new QTabWidget(tcManagerProject);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(9, 70, 1151, 601));
        tabWidget->setStyleSheet(QString::fromUtf8("color:\"black\""));
        tbAssigedProjects = new QWidget();
        tbAssigedProjects->setObjectName(QString::fromUtf8("tbAssigedProjects"));
        btnStartProjcet = new QPushButton(tbAssigedProjects);
        btnStartProjcet->setObjectName(QString::fromUtf8("btnStartProjcet"));
        btnStartProjcet->setGeometry(QRect(870, 514, 141, 41));
        btnStartProjcet->setStyleSheet(QString::fromUtf8("color:\"black\";"));
        dgAssignedProjects = new QTableView(tbAssigedProjects);
        dgAssignedProjects->setObjectName(QString::fromUtf8("dgAssignedProjects"));
        dgAssignedProjects->setGeometry(QRect(20, 50, 1091, 421));
        tabWidget->addTab(tbAssigedProjects, QString());
        tbCurrentProject = new QWidget();
        tbCurrentProject->setObjectName(QString::fromUtf8("tbCurrentProject"));
        btnCompleteProject = new QPushButton(tbCurrentProject);
        btnCompleteProject->setObjectName(QString::fromUtf8("btnCompleteProject"));
        btnCompleteProject->setGeometry(QRect(889, 514, 161, 41));
        dgCurrentProjects = new QTableView(tbCurrentProject);
        dgCurrentProjects->setObjectName(QString::fromUtf8("dgCurrentProjects"));
        dgCurrentProjects->setGeometry(QRect(30, 20, 1091, 461));
        tabWidget->addTab(tbCurrentProject, QString());
        tbCompletedProjects = new QWidget();
        tbCompletedProjects->setObjectName(QString::fromUtf8("tbCompletedProjects"));
        dgCompletedProjects = new QTableView(tbCompletedProjects);
        dgCompletedProjects->setObjectName(QString::fromUtf8("dgCompletedProjects"));
        dgCompletedProjects->setGeometry(QRect(10, 10, 1131, 501));
        tabWidget->addTab(tbCompletedProjects, QString());
        label_16 = new QLabel(tcManagerProject);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(0, 0, 1170, 61));
        label_16->setFont(font);
        label_16->setStyleSheet(QString::fromUtf8("color:\"Black\";"));
        label_16->setFrameShape(QFrame::Panel);
        label_16->setTextFormat(Qt::AutoText);
        label_16->setAlignment(Qt::AlignCenter);
        label_16->setWordWrap(false);
        btnManageProjects_2 = new QPushButton(managerhomescreen);
        btnManageProjects_2->setObjectName(QString::fromUtf8("btnManageProjects_2"));
        btnManageProjects_2->setGeometry(QRect(30, 30, 269, 48));
        btnManageProjects->raise();
        btnHome->raise();
        btnLogout->raise();
        btnManageEmp->raise();
        homeControlManager->raise();
        manageEmployeeControl->raise();
        manageProjectControl->raise();
        tcManagerProject->raise();
        btnManageProjects_2->raise();

        retranslateUi(managerhomescreen);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(managerhomescreen);
    } // setupUi

    void retranslateUi(QDialog *managerhomescreen)
    {
        managerhomescreen->setWindowTitle(QCoreApplication::translate("managerhomescreen", "Dialog", nullptr));
        btnManageProjects->setText(QCoreApplication::translate("managerhomescreen", "Manage Projects", nullptr));
        btnHome->setText(QCoreApplication::translate("managerhomescreen", "Home", nullptr));
        btnLogout->setText(QCoreApplication::translate("managerhomescreen", "Log Out", nullptr));
        btnManageEmp->setText(QCoreApplication::translate("managerhomescreen", "Manage Employees", nullptr));
        manageProjectControl->setTitle(QString());
        btnEditProject_2->setText(QCoreApplication::translate("managerhomescreen", "Edit", nullptr));
        btnDeleteProject_2->setText(QCoreApplication::translate("managerhomescreen", "Delete", nullptr));
        label_17->setText(QCoreApplication::translate("managerhomescreen", "Project Details", nullptr));
        btnAddProject_2->setText(QCoreApplication::translate("managerhomescreen", "Add", nullptr));
        btnAssignUser_2->setText(QCoreApplication::translate("managerhomescreen", "Assign User", nullptr));
        groupBox_2->setTitle(QString());
        label_12->setText(QCoreApplication::translate("managerhomescreen", "Project Name", nullptr));
        label_19->setText(QCoreApplication::translate("managerhomescreen", "Starting Month", nullptr));
        label_20->setText(QCoreApplication::translate("managerhomescreen", "Description", nullptr));
        label_21->setText(QCoreApplication::translate("managerhomescreen", "Department", nullptr));
        label_22->setText(QCoreApplication::translate("managerhomescreen", "Project Code", nullptr));
        cbStartingMonth->setCurrentText(QString());
        manageEmployeeControl->setTitle(QString());
        btnEditEmployee_2->setText(QCoreApplication::translate("managerhomescreen", "Edit", nullptr));
        label_18->setText(QCoreApplication::translate("managerhomescreen", "Employee Details", nullptr));
        btnDeleteEmployee_2->setText(QCoreApplication::translate("managerhomescreen", "Delete", nullptr));
        btnAddEmployee_2->setText(QCoreApplication::translate("managerhomescreen", "Add", nullptr));
        groupBox->setTitle(QString());
        label_9->setText(QCoreApplication::translate("managerhomescreen", "Password", nullptr));
        label_2->setText(QCoreApplication::translate("managerhomescreen", "Address", nullptr));
        label_5->setText(QCoreApplication::translate("managerhomescreen", "Department", nullptr));
        label_6->setText(QCoreApplication::translate("managerhomescreen", "User Role", nullptr));
        label_3->setText(QCoreApplication::translate("managerhomescreen", "Gender", nullptr));
        label_10->setText(QCoreApplication::translate("managerhomescreen", "Username", nullptr));
        label_11->setText(QCoreApplication::translate("managerhomescreen", "Employee Name", nullptr));
        homeControlManager->setTitle(QString());
        label->setText(QCoreApplication::translate("managerhomescreen", "Welcome to Work Mate", nullptr));
        label_4->setText(QCoreApplication::translate("managerhomescreen", "TextLabel", nullptr));
        label_7->setText(QCoreApplication::translate("managerhomescreen", "Not Started", nullptr));
        lblNotStartedCount_3->setText(QCoreApplication::translate("managerhomescreen", "5", nullptr));
        label_8->setText(QCoreApplication::translate("managerhomescreen", "TextLabel", nullptr));
        label_13->setText(QCoreApplication::translate("managerhomescreen", "In Progress", nullptr));
        lblInProgressCount_3->setText(QCoreApplication::translate("managerhomescreen", "5", nullptr));
        label_14->setText(QCoreApplication::translate("managerhomescreen", "Completed", nullptr));
        lblCompletedCount_3->setText(QCoreApplication::translate("managerhomescreen", "5", nullptr));
        lblNameHeader_3->setText(QCoreApplication::translate("managerhomescreen", "David Mosby", nullptr));
        lblRoleHeader_3->setText(QCoreApplication::translate("managerhomescreen", "Manager", nullptr));
        lblName_3->setText(QCoreApplication::translate("managerhomescreen", "David Mosby", nullptr));
        lblGender_3->setText(QCoreApplication::translate("managerhomescreen", "Male", nullptr));
        lblAddress_3->setText(QCoreApplication::translate("managerhomescreen", "Lacinia Road, Lacinia ", nullptr));
        lblDepartment_3->setText(QCoreApplication::translate("managerhomescreen", "Finance Department", nullptr));
        lblRole_3->setText(QCoreApplication::translate("managerhomescreen", "Manager", nullptr));
        lblUsername_3->setText(QCoreApplication::translate("managerhomescreen", "SandaruK", nullptr));
        label_15->setText(QCoreApplication::translate("managerhomescreen", "TextLabel", nullptr));
        pUserAvatar->setText(QCoreApplication::translate("managerhomescreen", "TextLabel", nullptr));
        tcManagerProject->setTitle(QString());
        btnStartProjcet->setText(QCoreApplication::translate("managerhomescreen", "Start Project", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tbAssigedProjects), QCoreApplication::translate("managerhomescreen", "Assigned Porjects", nullptr));
        btnCompleteProject->setText(QCoreApplication::translate("managerhomescreen", "Complete Project", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tbCurrentProject), QCoreApplication::translate("managerhomescreen", "Projects Inprogress", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tbCompletedProjects), QCoreApplication::translate("managerhomescreen", "Completed Projects", nullptr));
        label_16->setText(QCoreApplication::translate("managerhomescreen", "Project Details", nullptr));
        btnManageProjects_2->setText(QCoreApplication::translate("managerhomescreen", "My Projects", nullptr));
    } // retranslateUi

};

namespace Ui {
    class managerhomescreen: public Ui_managerhomescreen {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MANAGERHOMESCREEN_H
